### ISSUE TITLE
Support for Relay modern v12

### ISSUE THREAD

**Issue by huv1k** [richardguerre/use-relay-mock-environment#6]
Really great lib, I just wonder if you could add support for relay v12. Thanks 🚀

**Comment by matt-dalton** [comment]
Hi @huv1k ...in what way does it not work for you? I'm having some issues and wondering if it's the same thing.

Also in case you found a different solution...what was it?

**Comment by a-tokyo** [comment]
This PR adds support for newer versions of relay https://github.com/richardguerre/use-relay-mock-environment/pull/7
